# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohOh2Ll0jv-2MLRRCakMPEvsPiBlFIua
"""

from datasets import load_dataset

# 1. Download the dataset directly from Hugging Face
debater_dataset = load_dataset("NLP-Debater-Project/IBM-Debater-ArgKP")

# 2. View the dataset structure
print("--- Dataset Structure ---")
print(debater_dataset)

# 3. Convert the training split to a Pandas DataFrame to explore it easily
df_debater = debater_dataset["train"].to_pandas()

print("\n--- First 5 Rows ---")
df_debater.head()

from datasets import load_dataset
import pandas as pd

# --- 1. Load and merge all splits ---
ds = load_dataset("ibm/argument_quality_ranking_30k", "argument_quality_ranking")

df = pd.concat([
    pd.DataFrame(ds['train']),
    pd.DataFrame(ds['validation']),
    pd.DataFrame(ds['test'])
], ignore_index=True)

print(f"Total arguments before cleaning: {len(df)}")

# --- 2. Drop unused columns ---
df = df.drop(columns=['WA', 'MACE-P', 'set'])

# --- 3. Rename for clarity ---
df = df.rename(columns={
    'topic': 'policy',
    'stance_WA': 'stance',
    'stance_WA_conf': 'stance_confidence'
})

# --- 4. Inspect stance distribution ---
print("\nStance distribution:")
print(df['stance'].value_counts())

# --- 5. Handle neutral stance ---
# Neutral arguments (stance == 0) are ambiguous by definition.
# We keep them but flag them — do NOT discard, they are structurally
# interesting for coherence auditing.
df['stance_label'] = df['stance'].map({1: 'PRO', -1: 'CON', 0: 'NEUTRAL'})

print(f"\nNeutral arguments: {df[df['stance'] == 0].shape[0]}")
print(f"Low confidence stances (conf < 0.7): {df[df['stance_confidence'] < 0.7].shape[0]}")

# --- 6. Basic text cleaning ---
df['argument'] = df['argument'].str.strip()
df = df[df['argument'].str.len() >= 35]  # enforce dataset's own minimum

# --- 7. Add unique argument ID ---
df['arg_id'] = ['arg_' + str(i) for i in range(len(df))]

# --- 8. Final check ---
print(f"\nTotal arguments after cleaning: {len(df)}")
print(f"Unique policies: {df['policy'].nunique()}")
print(f"\nArguments per policy:")
print(df.groupby('policy')['argument'].count().describe())

print("\nSample:")
print(df[['arg_id', 'policy', 'argument', 'stance_label', 'stance_confidence']].head(3))

# --- 9. Save ---
df.to_csv('arguments_clean.csv', index=False)
print("\nSaved to arguments_clean.csv")

df_debater.info()

from sentence_transformers import SentenceTransformer
from sklearn.cluster import HDBSCAN
import numpy as nnp

#rename topic into policy
df_debater.rename(columns={'topic': 'policy'}, inplace=True)
df_debater

#check for duplicates
df_debater.duplicated().sum()
#

#check for unique arguments
df_debater['argument'].nunique()

#2. Group by the argument text and aggregate the unique policies
cross_policy_args = df_debater.groupby('argument')['policy'].agg(['unique', 'nunique'])

# 3. Filter for arguments that are attached to MORE THAN 1 unique policy
overlap = cross_policy_args[cross_policy_args['nunique'] > 1]

print(f"Total unique arguments used across multiple policies: {len(overlap)}")

# 4. Print the first 5 examples so you can physically see them
if len(overlap) > 0:
    print("\n--- EXAMPLES ---")
    for arg, row in overlap.head(5).iterrows():
        print(f"\nArgument: '{arg[:100]}...'")
        print(f"Used in Policies: {row['unique']}")
else:
    print("\nGood news! No arguments span multiple policies.")

import pandas as pd
import re
import unicodedata

def clean_ibm_text(text):
    if not isinstance(text, str):
        return ""

    # 1. Unicode Normalization (converts things like \xa0 to spaces)
    text = unicodedata.normalize('NFKD', text)

    # 2. Remove HTML artifacts and URLs
    text = re.sub(r'http[s]?://\S+', '', text)
    text = re.sub(r'<.*?>', '', text)

    # 3. Fix "Debater-specific" noise (e.g., specific ID tags if any)
    text = re.sub(r'\[\d+\]', '', text)

    # 4. Standardize Whitespace
    text = " ".join(text.split())

    return text

# Remove rows where the argument became empty after cleaning

df_debater['argument'] = df_debater['argument'].apply(clean_ibm_text)
df_debater

# Remove rows where the argument became empty after cleaning
df_debater = df_debater[df_debater['argument'] != '']
df_debater

# 2. Generate Embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df_debater['argument'].tolist(), show_progress_bar=True)

# 3. Clustering to find "True Topics"
# min_cluster_size determines the granularity of your graph nodes
clusterer = HDBSCAN(min_cluster_size=100, metric='euclidean')
df_debater['topic_id'] = clusterer.fit_predict(embeddings)

import torch
from sentence_transformers import SentenceTransformer

# 1. Verification: Stop if no GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
if device == "cpu":
    raise RuntimeError("GPU not found! Go to Runtime > Change runtime type and select T4 GPU.")
else:
    print(f"✅ Using GPU: {torch.cuda.get_device_name(0)}")

# 2. Optimized Model Loading
model = SentenceTransformer('all-MiniLM-L6-v2', device=device)

# 3. Fast Embedding
# 30k sentences with batch_size=128 should take < 3 mins
print("Starting embedding...")
embeddings = model.encode(
    df_debater['argument'].tolist(),
    batch_size=128,
    show_progress_bar=True,
    convert_to_tensor=True # Keeps data on GPU for next steps
)

# Install RAPIDS for Colab (Run this in a separate cell first)
# !pip install cudf-cu12 cuml-cu12 --extra-index-url=https://pypi.nvidia.com

from cuml.cluster import HDBSCAN as GPU_HDBSCAN

# This will run in seconds on the GPU
clusterer = GPU_HDBSCAN(min_cluster_size=100)
df_debater['cluster_id'] = clusterer.fit_predict(embeddings).get()

df_debater

#check how many -1 values in the cluster id
df_debater[df_debater['cluster_id'] == -1].count()

#save dataset with cluster_ids
df_debater.to_csv('debater_dataset_with_clusters.csv', index=False)

#check number of distinct cluster
df_debater['cluster_id'].nunique()

from sklearn.feature_extraction.text import TfidfVectorizer

def get_cluster_keywords(df, n_words=3):
    # Group text by cluster
    cluster_docs = df.groupby('cluster_id')['argument'].apply(lambda x: " ".join(x))

    # Run TF-IDF on these "cluster documents"
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(cluster_docs)
    feature_names = vectorizer.get_feature_names_out()

    topic_names = {}
    for i, cid in enumerate(cluster_docs.index):
        if cid == -1:
            topic_names[cid] = "Noise/Unclassified"
            continue

        # Get top keywords for this cluster
        row = tfidf_matrix.getrow(i).toarray()[0]
        top_indices = row.argsort()[-n_words:][::-1]
        keywords = [feature_names[idx] for idx in top_indices]
        topic_names[cid] = "Topic: " + " & ".join(keywords).title()

    return topic_names

# Apply to your dataframe
names_dict = get_cluster_keywords(df_debater)
df_debater['topic_name'] = df_debater['cluster_id'].map(names_dict)

df_debater

import pandas as pd
#open csv file
df_frames = pd.read_csv('arguments_with_frames.csv')
df_frames

#count unclassified topics
df_frames[df_frames['topic_name'] == 'Unclassified Noise'].count()



#check unique frames values
df_frames['frame'].unique()

#check counts for each frame value
df_frames['frame'].value_counts()

